optitrack_listener:
  ros__parameters:
    fixed_frame: "map"
    local_interface: '172.22.160.20'
    rigid_object_list:  'body_2,body_3'
    trackables:
      body_2:
        id: 1
        name: ground_plan_tool
      body_3:
        id: 4
        name: calibration_wand
    publish_tf: True